# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prayertimes < Formula
  desc "A CLI tool for retrieving Islamic prayer times"
  homepage "https://github.com/lanrey-waju/prayertimes"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.3/prayertimes_Darwin_x86_64.tar.gz"
      sha256 "65fb34ba001f4f68e3ea0aa1964348503aaac7290cf6b50a6df74d4791ff321f"

      def install
        bin.install "prayertimes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.3/prayertimes_Darwin_arm64.tar.gz"
      sha256 "305f5eff68aca4d2980d43f41518ca26ae476e949d517970c117d457f2c562a1"

      def install
        bin.install "prayertimes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.3/prayertimes_Linux_x86_64.tar.gz"
        sha256 "eb01e769ff81cf7ac9cc824cdc7f5762e7cb2fd91a785e406f976bd56477feaa"

        def install
          bin.install "prayertimes"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.3/prayertimes_Linux_arm64.tar.gz"
        sha256 "e708173d5bf379014dbd16c2a6f0217eb503db192ae1092966b14da237f125c5"

        def install
          bin.install "prayertimes"
        end
      end
    end
  end

  test do
    system "#{bin}/prayertimes", "--help"
  end
end
