# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prayertimes < Formula
  desc "A CLI tool for retrieving Islamic prayer times"
  homepage "https://github.com/lanrey-waju/prayertimes"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.4/prayertimes_Darwin_x86_64.tar.gz"
      sha256 "856dbe0435ba2a23f767e38bd2762c08ffa1d600e6e267cd6e9541dd7de36b59"

      def install
        bin.install "prayertimes"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.4/prayertimes_Darwin_arm64.tar.gz"
      sha256 "4b626751b782230027c73cd676a0906c8e53e69882a680ace2fd55372b94758a"

      def install
        bin.install "prayertimes"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.4/prayertimes_Linux_x86_64.tar.gz"
        sha256 "653e898c9ee9d2319bc498123fbc7afc331bfc270d2b24990d9349c2ea3d3150"

        def install
          bin.install "prayertimes"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Lanrey-waju/prayertimes/releases/download/v0.1.4/prayertimes_Linux_arm64.tar.gz"
        sha256 "1f0a8b14536eecf6a47f018a5eca49ecbe265204269f18b8ff9a8d8b370b9e3e"

        def install
          bin.install "prayertimes"
        end
      end
    end
  end

  test do
    system "#{bin}/prayertimes", "--help"
  end
end
